### ISSUE TITLE
StateMachine minimization crash

### ISSUE THREAD

**Issue by garamibence** [pallagj/machines-redux#2]
Given the following StateMachine definition. If I add a new expression `m2 = min(m1)` the whole page disappears, becomes blank.

```
StateMachine:
  name: m1
  charset: 0, 1
  states: S, 0, 1, 00, 01, 10, 11, _0_0, _0_1, _0_2, _1_0, _1_1, _1_2
  init: S
  accept: _0_0
  transitions:
    - S 0 0
    - S 1 1
    - 0 0 00
    - 0 1 01
    - 1 0 10
    - 1 1 11
    - 00 0 _0_0
    - 00 1 _1_2
    - 01 0 _1_0
    - 01 1 _0_1
    - 10 0 _1_1
    - 10 1 _0_2
    - 11 0 _0_1
    - 11 1 _1_0
    - _0_0 0 _0_1
    - _0_1 0 _0_2
    - _0_2 0 _0_0
    - _1_0 0 _1_2
    - _1_1 0 _1_0
    - _1_2 0 _1_1
    - _0_0 1 _1_0
    - _0_1 1 _1_1
    - _0_2 1 _1_2
    - _1_0 1 _0_0
    - _1_1 1 _0_1
    - _1_2 1 _0_2
```
