### ISSUE TITLE
StateMachine minimization non-complete FSM identification

### ISSUE THREAD

**Issue by garamibence** [pallagj/machines-redux#3]
Given the following non-complete deterministic StateMachine definition. If I add a new expression `m2 = min(m1)` it does not complain about its non-completeness, but draws an incomplete diagram, pasted below.
```
StateMachine:
  name: m1
  charset: 0, 1
  states: S, A, R
  init: S
  accept: A
  transitions:
    - S 0 A
    - S 1 R
```

![image](https://github.com/pallagj/machines-redux/assets/85867500/bfb4ca18-becd-4c28-ae68-bf0327b3d90c)
